#!/usr/bin/bash

rm -rf build

cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

cmake --build build


cmake -DCMAKE_BUILD_TYPE=Release -S . -B build-release

cmake --build build-release

sudo cmake --install build-release